/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import bdd.CBDD;
import bdd.CParametresStockageBDD;
import entites.Praticien;
import entites.RapportVisite;
import entites.Visiteur;
import java.awt.HeadlessException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import metier.CMetierRapportVisite;
import persistance.CListeRapportVisitePersistante;
import table.CTableRapportVisite;

/**
 *
 * @author Alexis
 */
public class JFrame_Ajouter extends javax.swing.JFrame {

    private int dernierId;
    private CMetierRapportVisite metierRapportVisite = new CMetierRapportVisite();

    public JFrame_Ajouter(int dernierId) throws HeadlessException {
        initComponents();
        this.dernierId = dernierId;
        this.jTextField_NumeroRapport.setText("" + (this.getDernierId() + 1));
        this.RemplirComboBoxVisiteur();
    }

    public int getDernierId() {
        return dernierId;
    }

    /**
     * Creates new form JFrame_Editer
     */
    public JFrame_Ajouter() {
        initComponents();
        this.jTextField_NumeroRapport.setText("" + this.getDernierId());
        this.RemplirComboBoxVisiteur();
    }

    /*public JFrame_Ajouter(int index){
        initComponents();
        this.jTextField_NumeroRapport.setText(""+this.getDernierId());
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_NumeroRapport = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_Praticien = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTextField_DateRapport = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_MotifVisite = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Bilan = new javax.swing.JTextArea();
        jButton_Precedent = new javax.swing.JButton();
        jButton_Suivant = new javax.swing.JButton();
        jButton_Nouveau = new javax.swing.JButton();
        jButton_Details = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_Quitter = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox_Visiteur = new javax.swing.JComboBox<>();

        setTitle("Ajouter un rapport de visite");

        jLabel1.setText("RAPPORTS DE VISITE");

        jLabel5.setText("Numéro rapport");

        jTextField_NumeroRapport.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_NumeroRapport.setEnabled(false);

        jLabel6.setText("Praticien");

        jComboBox_Praticien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Praticien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_PraticienActionPerformed(evt);
            }
        });

        jLabel7.setText("DateRapport");

        jTextField_DateRapport.setText("JJ/MM/AAAA");
        jTextField_DateRapport.setToolTipText("JJ/MM/AAAA");
        jTextField_DateRapport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_DateRapportActionPerformed(evt);
            }
        });

        jLabel2.setText("Motif Visite");

        jLabel3.setText("Bilan");

        jTextArea_Bilan.setColumns(20);
        jTextArea_Bilan.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Bilan);

        jButton_Precedent.setText("Précédent");

        jButton_Suivant.setText("Suivant");

        jButton_Nouveau.setText("Nouveau");
        jButton_Nouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NouveauActionPerformed(evt);
            }
        });

        jButton_Details.setText("Détails");

        jLabel4.setText("Offres d'échantillons");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Médicament", "Nb. echantillon"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton_Quitter.setText("Quitter");
        jButton_Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_QuitterActionPerformed(evt);
            }
        });

        jLabel8.setText("Visiteur");

        jComboBox_Visiteur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Visiteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_VisiteurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jButton_Precedent)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Suivant)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Nouveau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Quitter))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_MotifVisite, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(62, 62, 62))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_DateRapport, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_NumeroRapport)
                            .addComponent(jComboBox_Praticien, 0, 81, Short.MAX_VALUE)
                            .addComponent(jComboBox_Visiteur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Details)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_NumeroRapport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox_Praticien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Details))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox_Visiteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_DateRapport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_MotifVisite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Precedent)
                    .addComponent(jButton_Suivant)
                    .addComponent(jButton_Nouveau)
                    .addComponent(jButton_Quitter))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_DateRapportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_DateRapportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_DateRapportActionPerformed

    private void jButton_QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_QuitterActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton_QuitterActionPerformed

    private void jButton_NouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NouveauActionPerformed
        this.AjouterRapportVisite();
        this.setVisible(false);
    }//GEN-LAST:event_jButton_NouveauActionPerformed

    private void jComboBox_PraticienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_PraticienActionPerformed

    }//GEN-LAST:event_jComboBox_PraticienActionPerformed

    private void jComboBox_VisiteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_VisiteurActionPerformed

    }//GEN-LAST:event_jComboBox_VisiteurActionPerformed

    /**
     * Recupére l'id du visiteur sélectionner dans la comboBox. Les chaînes de
     * caractères de la comboBox sont composées comme ceci: id_visiteur - Nom
     * Prénom
     *
     * @return l'id du visiteur sélectionner
     */
    String GetVisiteurSelctionner() {
        String visiteur = this.jComboBox_Visiteur.getItemAt(this.jComboBox_Visiteur.getSelectedIndex());
        String id_visiteur = "";
        int i = 0;
        while (visiteur.charAt(i) != ' ') {
            id_visiteur = id_visiteur + visiteur.charAt(i);
            i++;
        }
        System.out.println(id_visiteur);
        return id_visiteur;
    }

    void RemplirComboBoxVisiteur() {
        String[] tabVisiteur = metierRapportVisite.RecupererTabVisiteur();
        jComboBox_Visiteur.setModel(new JComboBox(tabVisiteur).getModel());
    }

    public void AjouterRapportVisite() {
        CBDD bdd = new CBDD(new CParametresStockageBDD("parametresBdd.properties"));
        CTableRapportVisite tableRapportVisite = new CTableRapportVisite();
        tableRapportVisite.setBdd(bdd);

        CListeRapportVisitePersistante listeRapport = new CListeRapportVisitePersistante();
        listeRapport.setTableRapport(tableRapportVisite);
        listeRapport.chargerTable();

        int numero = Integer.parseInt(this.jTextField_NumeroRapport.getText());
        String bilan = this.jTextArea_Bilan.getText();
        String motif = this.jTextField_MotifVisite.getText();
        java.sql.Date date = tableRapportVisite.StringVersSQLDate("01/01/1970");
        try {
            date = tableRapportVisite.StringVersSQLDate(this.jTextField_DateRapport.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Date non valide (JJ/MM/AAAA)", "Date invalide", JOptionPane.ERROR_MESSAGE, null);
            date = tableRapportVisite.StringVersSQLDate("-1");
        }

        Visiteur visiteur = new Visiteur(this.GetVisiteurSelctionner());
        Praticien praticien = new Praticien(1);
        RapportVisite rapport = new RapportVisite(numero, date, bilan, motif, visiteur, praticien);
        listeRapport.InsererRapport(rapport);
        JOptionPane.showMessageDialog(null, "Rapport de visite ajouté", "Rapport ajouter", JOptionPane.INFORMATION_MESSAGE, null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Ajouter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Details;
    private javax.swing.JButton jButton_Nouveau;
    private javax.swing.JButton jButton_Precedent;
    private javax.swing.JButton jButton_Quitter;
    private javax.swing.JButton jButton_Suivant;
    private javax.swing.JComboBox<String> jComboBox_Praticien;
    private javax.swing.JComboBox<String> jComboBox_Visiteur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea_Bilan;
    private javax.swing.JTextField jTextField_DateRapport;
    private javax.swing.JTextField jTextField_MotifVisite;
    private javax.swing.JTextField jTextField_NumeroRapport;
    // End of variables declaration//GEN-END:variables
}
