/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import entites.RapportVisite;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import metier.CMetierRapportVisite;

/**
 *
 * @author Alexis
 */
public class JFrame_RapportVisite extends javax.swing.JFrame {

    private CMetierRapportVisite metierRapportVisite = new CMetierRapportVisite();

    /**
     * Creates new form JFrame_RapportVisite
     */
    public JFrame_RapportVisite() {
        initComponents();
        try {
            this.afficherInfosRapportVisite();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Impossible de récupérer les informations.", "Erreur", JOptionPane.ERROR_MESSAGE, null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_rapport = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton_Ajouter = new javax.swing.JButton();
        jButton_Supprimer = new javax.swing.JButton();
        jButton_Quitter = new javax.swing.JButton();
        jButton_Rafraichir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Affichage des rapports de visite");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTable_rapport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro", "Date", "Bilan", "Motif", "Visiteur", "Numéro Praticien"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_rapport);

        jLabel1.setText("Affichage des rapports de visite:");

        jButton_Ajouter.setText("Ajouter");
        jButton_Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AjouterActionPerformed(evt);
            }
        });

        jButton_Supprimer.setText("Supprimer");
        jButton_Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SupprimerActionPerformed(evt);
            }
        });

        jButton_Quitter.setText("Quitter");
        jButton_Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_QuitterActionPerformed(evt);
            }
        });

        jButton_Rafraichir.setText("Rafraichir");
        jButton_Rafraichir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RafraichirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton_Supprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Quitter, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton_Ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addComponent(jButton_Rafraichir)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_Ajouter)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Supprimer)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Rafraichir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addComponent(jButton_Quitter)
                        .addGap(30, 30, 30))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_QuitterActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton_QuitterActionPerformed

    private void jButton_AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AjouterActionPerformed
        int id = -1;
        try {
            id = metierRapportVisite.RecupererDernierIdRapportVisite();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Impossible de récuperer le dernier rapport de visite créer.", "Erreur", JOptionPane.ERROR_MESSAGE, null);
            Logger.getLogger(JFrame_RapportVisite.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (id != -1) {
            new JFrame_Ajouter(id).setVisible(true);
        }
    }//GEN-LAST:event_jButton_AjouterActionPerformed

    private void jButton_SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SupprimerActionPerformed
        this.SupprimerRapportVisite();
    }//GEN-LAST:event_jButton_SupprimerActionPerformed

    private void jButton_RafraichirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RafraichirActionPerformed
        RafraichirListe();
    }//GEN-LAST:event_jButton_RafraichirActionPerformed

    /**
     * Ajoute les informations dans le tableau
     */
    public void afficherInfosRapportVisite() {
        ArrayList<RapportVisite> list = metierRapportVisite.RecupererListeRapportVisite();
        DefaultTableModel model = (DefaultTableModel) jTable_rapport.getModel();
        Object[] row = new Object[6];

        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getNumero();
            row[1] = list.get(i).getDateString();
            row[2] = list.get(i).getBilan();
            row[3] = list.get(i).getMotif();
            row[4] = metierRapportVisite.RecupererNomPrenomVisiteur(list.get(i).getVisiteur().getMatricule());
            row[5] = list.get(i).getPraticien().getNumPraticien();
            model.addRow(row);
        }
    }

    /**
     * Rafraichit les rapports de visite dans le tableau.
     */
    public void RafraichirListe() {
        DefaultTableModel model = (DefaultTableModel) jTable_rapport.getModel();
        model.setRowCount(0);
        try {
            this.afficherInfosRapportVisite();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Impossible de rafraîchir le tableau.", "Erreur", JOptionPane.ERROR_MESSAGE, null);
        }
    }

    /**
     * Supprime le rapport de visite sélectionner.
     */
    public void SupprimerRapportVisite() {
        try {
            int index = Integer.parseInt(this.jTable_rapport.getValueAt(this.jTable_rapport.getSelectedRow(), 0).toString());
            metierRapportVisite.SupprimerRapportVisite(index);
            RafraichirListe();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Aucun rapport sélectionner.", "Erreur", JOptionPane.ERROR_MESSAGE, null);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_RapportVisite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_RapportVisite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_RapportVisite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_RapportVisite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_RapportVisite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Ajouter;
    private javax.swing.JButton jButton_Quitter;
    private javax.swing.JButton jButton_Rafraichir;
    private javax.swing.JButton jButton_Supprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_rapport;
    // End of variables declaration//GEN-END:variables
}
